name: indhuskai_diary
description: Indhu'sKai App - Magical diary starter
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.3.0
  just_audio: ^0.9.34
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/magic_sparkles.json
    - assets/animations/kai_sparkle.json
    - assets/animations/sticker_sparkle.json
    - assets/stickers/magic_star.png
